// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
//   protoc-gen-go v1.34.2
//   protoc        v5.27.1
// source: proto/alert.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AgentRegistration is sent by an agent when it first connects to the
// dashboard server. The server uses the agent_cn field (populated from
// the mTLS client certificate Common Name) as the authoritative agent
// identity.
type AgentRegistration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// AgentCn is the Common Name extracted from the agent's mTLS certificate.
	AgentCn string `protobuf:"bytes,1,opt,name=agent_cn,json=agentCn,proto3" json:"agent_cn,omitempty"`
	// Hostname is the OS-reported hostname of the agent machine.
	Hostname string `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// Platform is the operating system platform string (e.g. "linux/amd64").
	Platform string `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	// AgentVersion is the human-readable version of the agent binary.
	AgentVersion string `protobuf:"bytes,4,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	// IpAddress is the dotted-decimal primary IP address of the agent.
	IpAddress string `protobuf:"bytes,5,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
}

func (x *AgentRegistration) Reset() {
	*x = AgentRegistration{}
	mi := &file_proto_alert_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRegistration) ProtoMessage() {}

func (x *AgentRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alert_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRegistration.ProtoReflect.Descriptor instead.
func (*AgentRegistration) Descriptor() ([]byte, []int) {
	return file_proto_alert_proto_rawDescGZIP(), []int{0}
}

func (x *AgentRegistration) GetAgentCn() string {
	if x != nil {
		return x.AgentCn
	}
	return ""
}

func (x *AgentRegistration) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentRegistration) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *AgentRegistration) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *AgentRegistration) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

// AgentEvent is a single alert event streamed from an agent to the dashboard.
type AgentEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// HostId is the UUID of the host that generated this event.
	HostId string `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	// TimestampMs is the Unix time in milliseconds when the event occurred.
	TimestampMs int64 `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	// TripwireType is the category of the sensor: FILE, NETWORK, or PROCESS.
	TripwireType string `protobuf:"bytes,3,opt,name=tripwire_type,json=tripwireType,proto3" json:"tripwire_type,omitempty"`
	// RuleName is the human-readable identifier of the tripwire rule.
	RuleName string `protobuf:"bytes,4,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`
	// Severity is the configured urgency level: INFO, WARN, or CRITICAL.
	Severity string `protobuf:"bytes,5,opt,name=severity,proto3" json:"severity,omitempty"`
	// EventDetail is an opaque JSON payload carrying sensor-specific context.
	EventDetail []byte `protobuf:"bytes,6,opt,name=event_detail,json=eventDetail,proto3" json:"event_detail,omitempty"`
}

func (x *AgentEvent) Reset() {
	*x = AgentEvent{}
	mi := &file_proto_alert_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEvent) ProtoMessage() {}

func (x *AgentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alert_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEvent.ProtoReflect.Descriptor instead.
func (*AgentEvent) Descriptor() ([]byte, []int) {
	return file_proto_alert_proto_rawDescGZIP(), []int{1}
}

func (x *AgentEvent) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *AgentEvent) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *AgentEvent) GetTripwireType() string {
	if x != nil {
		return x.TripwireType
	}
	return ""
}

func (x *AgentEvent) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

func (x *AgentEvent) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *AgentEvent) GetEventDetail() []byte {
	if x != nil {
		return x.EventDetail
	}
	return nil
}

// ServerAck is the server's per-event acknowledgement sent back to the agent
// over the StreamAlerts bidirectional stream.
type ServerAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Ok indicates whether the event was successfully processed and persisted.
	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// AlertId is the UUID assigned to the persisted alert when ok is true.
	AlertId string `protobuf:"bytes,2,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	// Error is a human-readable description of the failure when ok is false.
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ServerAck) Reset() {
	*x = ServerAck{}
	mi := &file_proto_alert_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerAck) ProtoMessage() {}

func (x *ServerAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alert_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerAck.ProtoReflect.Descriptor instead.
func (*ServerAck) Descriptor() ([]byte, []int) {
	return file_proto_alert_proto_rawDescGZIP(), []int{2}
}

func (x *ServerAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ServerAck) GetAlertId() string {
	if x != nil {
		return x.AlertId
	}
	return ""
}

func (x *ServerAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ─── File descriptor ─────────────────────────────────────────────────────────

// file_proto_alert_proto_rawDesc is the uncompressed proto binary
// FileDescriptorProto for proto/alert.proto, generated from the proto source
// using a Node.js encoder script (internal/proto/gen/gen.js).
//
// Do not edit by hand; regenerate from the proto source when the schema changes.
var file_proto_alert_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33, 0x22, 0xaa, 0x01, 0x0a, 0x11, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x5f, 0x63, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x43, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x23, 0x0a, 0x0d, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x70, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22,
	0xc9, 0x01, 0x0a, 0x0a, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x5f, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x4d, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x72,
	0x69, 0x70, 0x77, 0x69, 0x72, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x74, 0x72, 0x69, 0x70, 0x77, 0x69, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x72, 0x75, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x72, 0x75, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x73, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x73, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x22, 0x4c, 0x0a, 0x09, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x63, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x6c, 0x65, 0x72,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x6c, 0x65, 0x72,
	0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32, 0x84, 0x01, 0x0a, 0x0c, 0x41, 0x6c,
	0x65, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x0d, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x2e, 0x61, 0x6c,
	0x65, 0x72, 0x74, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x10, 0x2e, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x2e, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x41, 0x63, 0x6b, 0x12, 0x37, 0x0a, 0x0c, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x73, 0x12, 0x11, 0x2e, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x2e,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x1a, 0x10, 0x2e, 0x61, 0x6c, 0x65,
	0x72, 0x74, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x63, 0x6b, 0x28, 0x01, 0x30, 0x01,
	0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74,
	0x72, 0x69, 0x70, 0x77, 0x69, 0x72, 0x65, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f,
}

var (
	file_proto_alert_proto_rawDescOnce sync.Once
	file_proto_alert_proto_rawDescData []byte
)

func file_proto_alert_proto_rawDescGZIP() []byte {
	file_proto_alert_proto_rawDescOnce.Do(func() {
		file_proto_alert_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_alert_proto_rawDesc)
	})
	return file_proto_alert_proto_rawDescData
}

var file_proto_alert_proto_msgTypes = make([]protoimpl.MessageInfo, 3)

var file_proto_alert_proto_goTypes = []any{
	(*AgentRegistration)(nil), // 0: alert.AgentRegistration
	(*AgentEvent)(nil),        // 1: alert.AgentEvent
	(*ServerAck)(nil),         // 2: alert.ServerAck
}

// file_proto_alert_proto_depIdxs maps protobuf dependency indices.
// The AlertService has two methods:
//
//	RegisterAgent: input=AgentRegistration(0), output=ServerAck(2)
//	StreamAlerts:  input=AgentEvent(1),        output=ServerAck(2)
var file_proto_alert_proto_depIdxs = []int32{
	0, // 0: alert.AlertService.RegisterAgent:input_type  -> alert.AgentRegistration
	1, // 1: alert.AlertService.StreamAlerts:input_type   -> alert.AgentEvent
	2, // 2: alert.AlertService.RegisterAgent:output_type -> alert.ServerAck
	2, // 3: alert.AlertService.StreamAlerts:output_type  -> alert.ServerAck
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

// File_proto_alert_proto is the protoreflect.FileDescriptor for proto/alert.proto.
var File_proto_alert_proto protoreflect.FileDescriptor

func init() { file_proto_alert_proto_init() }

func file_proto_alert_proto_init() {
	if File_proto_alert_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_alert_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AgentRegistration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_alert_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AgentEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_alert_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ServerAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_alert_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		}.Build(),
		GoTypes:           file_proto_alert_proto_goTypes,
		DependencyIndexes: file_proto_alert_proto_depIdxs,
		MessageInfos:      file_proto_alert_proto_msgTypes,
	}.Build()
	File_proto_alert_proto = out.File
	file_proto_alert_proto_rawDescData = nil
	file_proto_alert_proto_goTypes = nil
	file_proto_alert_proto_depIdxs = nil
}

// Ensure the unsafe import is used (required for protoimpl.Pointer conversions).
var _ = unsafe.Sizeof(0)
