// Code generated by protoc-gen-go. DO NOT EDIT.
// Regenerate with:
//
//go:generate protoc --go_out=. --go_opt=paths=source_relative \
//                   --go-grpc_out=. --go-grpc_opt=paths=source_relative \
//                   proto/alert.proto
//
// source: proto/alert.proto

package alert

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

// AgentEvent is a single alert generated by a watcher on the monitored host.
//
// It is sent by the agent over the StreamAlerts bidirectional stream.
type AgentEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// alert_id is a client-generated UUID for idempotent replay support.
	AlertId string `protobuf:"bytes,1,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	// host_id is the dashboard-assigned UUID for this agent (from RegisterAgent).
	HostId string `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	// timestamp_us is the event occurrence time as Unix microseconds (agent clock).
	TimestampUs int64 `protobuf:"varint,3,opt,name=timestamp_us,json=timestampUs,proto3" json:"timestamp_us,omitempty"`
	// tripwire_type is one of "FILE", "NETWORK", or "PROCESS".
	TripwireType string `protobuf:"bytes,4,opt,name=tripwire_type,json=tripwireType,proto3" json:"tripwire_type,omitempty"`
	// rule_name is the human-readable name of the TripwireRule that fired.
	RuleName string `protobuf:"bytes,5,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`
	// event_detail_json is an opaque JSON blob carrying type-specific metadata.
	EventDetailJson []byte `protobuf:"bytes,6,opt,name=event_detail_json,json=eventDetailJson,proto3" json:"event_detail_json,omitempty"`
	// severity is one of "INFO", "WARN", or "CRITICAL".
	Severity string `protobuf:"bytes,7,opt,name=severity,proto3" json:"severity,omitempty"`
}

func (x *AgentEvent) Reset()         { *x = AgentEvent{} }
func (x *AgentEvent) String() string { return x.AlertId }
func (*AgentEvent) ProtoMessage()    {}

func (x *AgentEvent) ProtoReflect() protoreflect.Message {
	mi := &agentEventMsgInfo
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var agentEventMsgInfo = protoimpl.MessageInfo{GoReflectType: nil}

func (x *AgentEvent) GetAlertId() string        { return x.AlertId }
func (x *AgentEvent) GetHostId() string          { return x.HostId }
func (x *AgentEvent) GetTimestampUs() int64      { return x.TimestampUs }
func (x *AgentEvent) GetTripwireType() string    { return x.TripwireType }
func (x *AgentEvent) GetRuleName() string        { return x.RuleName }
func (x *AgentEvent) GetEventDetailJson() []byte { return x.EventDetailJson }
func (x *AgentEvent) GetSeverity() string        { return x.Severity }

// RegisterRequest is sent by the agent once to establish its identity.
//
// The server uses this to upsert a Host record and return a stable host_id.
type RegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// hostname is the FQDN or short hostname of the monitored host.
	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// platform is "linux", "darwin", or "windows".
	Platform string `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	// agent_version is the semantic version of the agent binary (e.g. "1.2.3").
	AgentVersion string `protobuf:"bytes,3,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
}

func (x *RegisterRequest) Reset()         { *x = RegisterRequest{} }
func (x *RegisterRequest) String() string { return x.Hostname }
func (*RegisterRequest) ProtoMessage()    {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &registerRequestMsgInfo
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var registerRequestMsgInfo = protoimpl.MessageInfo{GoReflectType: nil}

func (x *RegisterRequest) GetHostname() string     { return x.Hostname }
func (x *RegisterRequest) GetPlatform() string     { return x.Platform }
func (x *RegisterRequest) GetAgentVersion() string { return x.AgentVersion }

// RegisterResponse is returned by the dashboard after a successful
// RegisterAgent call.
type RegisterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// host_id is the server-assigned UUID for this host.  Agents must embed
	// this value in every AgentEvent.host_id field.
	HostId string `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	// server_time_us is the server's current time as Unix microseconds.
	// Agents may use this to detect large clock skew.
	ServerTimeUs int64 `protobuf:"varint,2,opt,name=server_time_us,json=serverTimeUs,proto3" json:"server_time_us,omitempty"`
}

func (x *RegisterResponse) Reset()         { *x = RegisterResponse{} }
func (x *RegisterResponse) String() string { return x.HostId }
func (*RegisterResponse) ProtoMessage()    {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &registerResponseMsgInfo
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var registerResponseMsgInfo = protoimpl.MessageInfo{GoReflectType: nil}

func (x *RegisterResponse) GetHostId() string      { return x.HostId }
func (x *RegisterResponse) GetServerTimeUs() int64 { return x.ServerTimeUs }

// ServerCommand is sent by the dashboard to the agent over the StreamAlerts
// response stream.  Currently used for per-event ACK/ERROR signalling.
type ServerCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// type identifies the command, e.g. "ACK", "ERROR", "RELOAD_RULES".
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// payload is an optional JSON-encoded body for the command.
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *ServerCommand) Reset()         { *x = ServerCommand{} }
func (x *ServerCommand) String() string { return x.Type }
func (*ServerCommand) ProtoMessage()    {}

func (x *ServerCommand) ProtoReflect() protoreflect.Message {
	mi := &serverCommandMsgInfo
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var serverCommandMsgInfo = protoimpl.MessageInfo{GoReflectType: nil}

func (x *ServerCommand) GetType() string    { return x.Type }
func (x *ServerCommand) GetPayload() []byte { return x.Payload }
