// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
//   protoc-gen-go-grpc v1.4.0
//   protoc             v5.27.1
// source: proto/alert.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	AlertService_RegisterAgent_FullMethodName = "/alert.AlertService/RegisterAgent"
	AlertService_StreamAlerts_FullMethodName  = "/alert.AlertService/StreamAlerts"
)

// ─── Client ──────────────────────────────────────────────────────────────────

// AlertServiceClient is the client API for AlertService.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer
// to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AlertServiceClient interface {
	// RegisterAgent is called once per connection to record the agent identity.
	RegisterAgent(ctx context.Context, in *AgentRegistration, opts ...grpc.CallOption) (*ServerAck, error)
	// StreamAlerts is a bidirectional streaming RPC.
	StreamAlerts(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentEvent, ServerAck], error)
}

type alertServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAlertServiceClient(cc grpc.ClientConnInterface) AlertServiceClient {
	return &alertServiceClient{cc}
}

func (c *alertServiceClient) RegisterAgent(ctx context.Context, in *AgentRegistration, opts ...grpc.CallOption) (*ServerAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerAck)
	err := c.cc.Invoke(ctx, AlertService_RegisterAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertServiceClient) StreamAlerts(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentEvent, ServerAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AlertService_ServiceDesc.Streams[0], AlertService_StreamAlerts_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentEvent, ServerAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code
// that references the pre-generic stream type by name.
type AlertService_StreamAlertsClient = grpc.BidiStreamingClient[AgentEvent, ServerAck]

// ─── Server ──────────────────────────────────────────────────────────────────

// AlertServiceServer is the server API for AlertService.
// All implementations must embed UnimplementedAlertServiceServer for forward
// compatibility.
type AlertServiceServer interface {
	// RegisterAgent is called once per connection to record the agent identity.
	RegisterAgent(context.Context, *AgentRegistration) (*ServerAck, error)
	// StreamAlerts is a bidirectional streaming RPC.
	StreamAlerts(grpc.BidiStreamingServer[AgentEvent, ServerAck]) error
	mustEmbedUnimplementedAlertServiceServer()
}

// This type alias is provided for backwards compatibility with existing code
// that references the pre-generic stream type by name.
type AlertService_StreamAlertsServer = grpc.BidiStreamingServer[AgentEvent, ServerAck]

// UnimplementedAlertServiceServer must be embedded to have forward compatible
// implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAlertServiceServer struct{}

func (UnimplementedAlertServiceServer) RegisterAgent(context.Context, *AgentRegistration) (*ServerAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterAgent not implemented")
}

func (UnimplementedAlertServiceServer) StreamAlerts(grpc.BidiStreamingServer[AgentEvent, ServerAck]) error {
	return status.Errorf(codes.Unimplemented, "method StreamAlerts not implemented")
}

func (UnimplementedAlertServiceServer) mustEmbedUnimplementedAlertServiceServer() {}

// UnsafeAlertServiceServer may be embedded to opt out of forward compatibility
// for this service. Use of this interface is not recommended, as added methods
// to AlertServiceServer will result in compilation errors.
type UnsafeAlertServiceServer interface {
	mustEmbedUnimplementedAlertServiceServer()
}

// RegisterAlertServiceServer registers the AlertServiceServer implementation
// with the gRPC server s.
func RegisterAlertServiceServer(s grpc.ServiceRegistrar, srv AlertServiceServer) {
	s.RegisterService(&AlertService_ServiceDesc, srv)
}

func _AlertService_RegisterAgent_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(AgentRegistration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertServiceServer).RegisterAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertService_RegisterAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(AlertServiceServer).RegisterAgent(ctx, req.(*AgentRegistration))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertService_StreamAlerts_Handler(srv any, stream grpc.ServerStream) error {
	return srv.(AlertServiceServer).StreamAlerts(&grpc.GenericServerStream[AgentEvent, ServerAck]{ServerStream: stream})
}

// AlertService_ServiceDesc is the grpc.ServiceDesc for AlertService service.
// It is for internal use only, proper use is via RegisterAlertServiceServer function.
var AlertService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "alert.AlertService",
	HandlerType: (*AlertServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAgent",
			Handler:    _AlertService_RegisterAgent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAlerts",
			Handler:       _AlertService_StreamAlerts_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/alert.proto",
}
