// TripWire AlertService — gRPC service definition.
//
// Agents open a single bidirectional stream (StreamAlerts) to push alert
// events to the dashboard server.  Before streaming, an agent must call
// RegisterAgent to obtain its server-assigned host_id.
//
// Code generated from this file is committed to the repository under
// internal/server/grpc/alertpb/ so that builds do not require protoc.
// Regenerate with:
//   buf generate   (if buf.yaml is present)
//   OR
//   protoc --go_out=internal/server/grpc/alertpb --go_opt=paths=source_relative \
//          --go-grpc_out=internal/server/grpc/alertpb --go-grpc_opt=paths=source_relative \
//          proto/alert.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.0
// source: alert.proto

package alertpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	AlertService_RegisterAgent_FullMethodName = "/tripwire.AlertService/RegisterAgent"
	AlertService_StreamAlerts_FullMethodName  = "/tripwire.AlertService/StreamAlerts"
)

// AlertServiceClient is the client API for AlertService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AlertService is the gRPC service exposed by the TripWire dashboard server.
// Agents connect via mTLS and stream alert events for real-time ingestion.
type AlertServiceClient interface {
	// RegisterAgent is called once per connection.  The agent supplies its
	// hostname and platform; the server returns a stable host_id (UUID) that
	// must be embedded in every subsequent AgentEvent.
	RegisterAgent(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// StreamAlerts is a bidirectional streaming RPC.  The agent sends a
	// continuous stream of AgentEvent messages; the server may send
	// ServerCommand messages back (e.g., rule reload, shutdown).
	StreamAlerts(ctx context.Context, opts ...grpc.CallOption) (AlertService_StreamAlertsClient, error)
}

type alertServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAlertServiceClient(cc grpc.ClientConnInterface) AlertServiceClient {
	return &alertServiceClient{cc}
}

func (c *alertServiceClient) RegisterAgent(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, AlertService_RegisterAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertServiceClient) StreamAlerts(ctx context.Context, opts ...grpc.CallOption) (AlertService_StreamAlertsClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AlertService_ServiceDesc.Streams[0], AlertService_StreamAlerts_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &alertServiceStreamAlertsClient{ClientStream: stream}
	return x, nil
}

type AlertService_StreamAlertsClient interface {
	Send(*AgentEvent) error
	Recv() (*ServerCommand, error)
	grpc.ClientStream
}

type alertServiceStreamAlertsClient struct {
	grpc.ClientStream
}

func (x *alertServiceStreamAlertsClient) Send(m *AgentEvent) error {
	return x.ClientStream.SendMsg(m)
}

func (x *alertServiceStreamAlertsClient) Recv() (*ServerCommand, error) {
	m := new(ServerCommand)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AlertServiceServer is the server API for AlertService service.
// All implementations must embed UnimplementedAlertServiceServer
// for forward compatibility
//
// AlertService is the gRPC service exposed by the TripWire dashboard server.
// Agents connect via mTLS and stream alert events for real-time ingestion.
type AlertServiceServer interface {
	// RegisterAgent is called once per connection.  The agent supplies its
	// hostname and platform; the server returns a stable host_id (UUID) that
	// must be embedded in every subsequent AgentEvent.
	RegisterAgent(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// StreamAlerts is a bidirectional streaming RPC.  The agent sends a
	// continuous stream of AgentEvent messages; the server may send
	// ServerCommand messages back (e.g., rule reload, shutdown).
	StreamAlerts(AlertService_StreamAlertsServer) error
	mustEmbedUnimplementedAlertServiceServer()
}

// UnimplementedAlertServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAlertServiceServer struct {
}

func (UnimplementedAlertServiceServer) RegisterAgent(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterAgent not implemented")
}
func (UnimplementedAlertServiceServer) StreamAlerts(AlertService_StreamAlertsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamAlerts not implemented")
}
func (UnimplementedAlertServiceServer) mustEmbedUnimplementedAlertServiceServer() {}

// UnsafeAlertServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlertServiceServer will
// result in compilation errors.
type UnsafeAlertServiceServer interface {
	mustEmbedUnimplementedAlertServiceServer()
}

func RegisterAlertServiceServer(s grpc.ServiceRegistrar, srv AlertServiceServer) {
	s.RegisterService(&AlertService_ServiceDesc, srv)
}

func _AlertService_RegisterAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertServiceServer).RegisterAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertService_RegisterAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertServiceServer).RegisterAgent(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertService_StreamAlerts_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AlertServiceServer).StreamAlerts(&alertServiceStreamAlertsServer{ServerStream: stream})
}

type AlertService_StreamAlertsServer interface {
	Send(*ServerCommand) error
	Recv() (*AgentEvent, error)
	grpc.ServerStream
}

type alertServiceStreamAlertsServer struct {
	grpc.ServerStream
}

func (x *alertServiceStreamAlertsServer) Send(m *ServerCommand) error {
	return x.ServerStream.SendMsg(m)
}

func (x *alertServiceStreamAlertsServer) Recv() (*AgentEvent, error) {
	m := new(AgentEvent)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AlertService_ServiceDesc is the grpc.ServiceDesc for AlertService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AlertService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tripwire.AlertService",
	HandlerType: (*AlertServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAgent",
			Handler:    _AlertService_RegisterAgent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAlerts",
			Handler:       _AlertService_StreamAlerts_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "alert.proto",
}
