// Code generated by protoc-gen-go. DO NOT EDIT.
// Regenerate with:
//   protoc --go_out=. --go_opt=paths=source_relative \
//          --go-grpc_out=. --go-grpc_opt=paths=source_relative \
//          proto/alert.proto
//
// This file contains hand-written stubs that will be replaced by protoc output
// when a build environment with protoc is available.  The message structs and
// gRPC service interfaces are correct and match the proto definition; only the
// proto reflection machinery is simplified (no file descriptor registration).
//
// source: proto/alert.proto

package alert

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

// AgentEvent is a single alert generated by a watcher on the monitored host.
type AgentEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AlertId         string `protobuf:"bytes,1,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	HostId          string `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	TimestampUs     int64  `protobuf:"varint,3,opt,name=timestamp_us,json=timestampUs,proto3" json:"timestamp_us,omitempty"`
	TripwireType    string `protobuf:"bytes,4,opt,name=tripwire_type,json=tripwireType,proto3" json:"tripwire_type,omitempty"`
	RuleName        string `protobuf:"bytes,5,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`
	EventDetailJson []byte `protobuf:"bytes,6,opt,name=event_detail_json,json=eventDetailJson,proto3" json:"event_detail_json,omitempty"`
	Severity        string `protobuf:"bytes,7,opt,name=severity,proto3" json:"severity,omitempty"`
}

func (x *AgentEvent) Reset()         { *x = AgentEvent{} }
func (x *AgentEvent) String() string { return x.AlertId }
func (*AgentEvent) ProtoMessage()    {}

func (x *AgentEvent) ProtoReflect() protoreflect.Message {
	mi := &agentEventMsgInfo
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var agentEventMsgInfo = protoimpl.MessageInfo{GoReflectType: nil}

func (x *AgentEvent) GetAlertId() string        { return x.AlertId }
func (x *AgentEvent) GetHostId() string          { return x.HostId }
func (x *AgentEvent) GetTimestampUs() int64      { return x.TimestampUs }
func (x *AgentEvent) GetTripwireType() string    { return x.TripwireType }
func (x *AgentEvent) GetRuleName() string        { return x.RuleName }
func (x *AgentEvent) GetEventDetailJson() []byte { return x.EventDetailJson }
func (x *AgentEvent) GetSeverity() string        { return x.Severity }

// RegisterRequest is sent by the agent once to establish its identity.
type RegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hostname     string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Platform     string `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	AgentVersion string `protobuf:"bytes,3,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
}

func (x *RegisterRequest) Reset()         { *x = RegisterRequest{} }
func (x *RegisterRequest) String() string { return x.Hostname }
func (*RegisterRequest) ProtoMessage()    {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &registerRequestMsgInfo
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var registerRequestMsgInfo = protoimpl.MessageInfo{GoReflectType: nil}

func (x *RegisterRequest) GetHostname() string     { return x.Hostname }
func (x *RegisterRequest) GetPlatform() string     { return x.Platform }
func (x *RegisterRequest) GetAgentVersion() string { return x.AgentVersion }

// RegisterResponse carries the dashboard-assigned host_id.
type RegisterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostId       string `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	ServerTimeUs int64  `protobuf:"varint,2,opt,name=server_time_us,json=serverTimeUs,proto3" json:"server_time_us,omitempty"`
}

func (x *RegisterResponse) Reset()         { *x = RegisterResponse{} }
func (x *RegisterResponse) String() string { return x.HostId }
func (*RegisterResponse) ProtoMessage()    {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &registerResponseMsgInfo
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var registerResponseMsgInfo = protoimpl.MessageInfo{GoReflectType: nil}

func (x *RegisterResponse) GetHostId() string      { return x.HostId }
func (x *RegisterResponse) GetServerTimeUs() int64 { return x.ServerTimeUs }

// ServerCommand is the per-event response from dashboard to agent.
type ServerCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *ServerCommand) Reset()         { *x = ServerCommand{} }
func (x *ServerCommand) String() string { return x.Type }
func (*ServerCommand) ProtoMessage()    {}

func (x *ServerCommand) ProtoReflect() protoreflect.Message {
	mi := &serverCommandMsgInfo
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var serverCommandMsgInfo = protoimpl.MessageInfo{GoReflectType: nil}

func (x *ServerCommand) GetType() string    { return x.Type }
func (x *ServerCommand) GetPayload() []byte { return x.Payload }
