// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// Regenerate with:
//   protoc --go_out=. --go_opt=paths=source_relative \
//          --go-grpc_out=. --go-grpc_opt=paths=source_relative \
//          proto/alert.proto
// source: proto/alert.proto

package alert

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// AlertServiceClient is the client API for AlertService service.
type AlertServiceClient interface {
	StreamAlerts(ctx context.Context, opts ...grpc.CallOption) (AlertService_StreamAlertsClient, error)
	RegisterAgent(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
}

type alertServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAlertServiceClient(cc grpc.ClientConnInterface) AlertServiceClient {
	return &alertServiceClient{cc}
}

func (c *alertServiceClient) StreamAlerts(ctx context.Context, opts ...grpc.CallOption) (AlertService_StreamAlertsClient, error) {
	stream, err := c.cc.NewStream(ctx, &AlertService_ServiceDesc.Streams[0], "/alert.AlertService/StreamAlerts", opts...)
	if err != nil {
		return nil, err
	}
	x := &alertServiceStreamAlertsClient{stream}
	return x, nil
}

type AlertService_StreamAlertsClient interface {
	Send(*AgentEvent) error
	Recv() (*ServerCommand, error)
	grpc.ClientStream
}

type alertServiceStreamAlertsClient struct {
	grpc.ClientStream
}

func (x *alertServiceStreamAlertsClient) Send(m *AgentEvent) error {
	return x.ClientStream.SendMsg(m)
}

func (x *alertServiceStreamAlertsClient) Recv() (*ServerCommand, error) {
	m := new(ServerCommand)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *alertServiceClient) RegisterAgent(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/alert.AlertService/RegisterAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlertServiceServer is the server API for AlertService service.
// All implementations must embed UnimplementedAlertServiceServer
// for forward compatibility.
type AlertServiceServer interface {
	StreamAlerts(AlertService_StreamAlertsServer) error
	RegisterAgent(context.Context, *RegisterRequest) (*RegisterResponse, error)
	mustEmbedUnimplementedAlertServiceServer()
}

// UnimplementedAlertServiceServer must be embedded to have forward compatible
// implementations.
type UnimplementedAlertServiceServer struct{}

func (UnimplementedAlertServiceServer) StreamAlerts(AlertService_StreamAlertsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamAlerts not implemented")
}
func (UnimplementedAlertServiceServer) RegisterAgent(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterAgent not implemented")
}
func (UnimplementedAlertServiceServer) mustEmbedUnimplementedAlertServiceServer() {}

// UnsafeAlertServiceServer may be embedded to opt out of forward compatibility.
type UnsafeAlertServiceServer interface {
	mustEmbedUnimplementedAlertServiceServer()
}

// AlertService_StreamAlertsServer is the server-side stream for StreamAlerts.
type AlertService_StreamAlertsServer interface {
	Send(*ServerCommand) error
	Recv() (*AgentEvent, error)
	grpc.ServerStream
}

type alertServiceStreamAlertsServer struct {
	grpc.ServerStream
}

func (x *alertServiceStreamAlertsServer) Send(m *ServerCommand) error {
	return x.ServerStream.SendMsg(m)
}

func (x *alertServiceStreamAlertsServer) Recv() (*AgentEvent, error) {
	m := new(AgentEvent)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func RegisterAlertServiceServer(s grpc.ServiceRegistrar, srv AlertServiceServer) {
	s.RegisterService(&AlertService_ServiceDesc, srv)
}

func _AlertService_StreamAlerts_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AlertServiceServer).StreamAlerts(&alertServiceStreamAlertsServer{stream})
}

func _AlertService_RegisterAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertServiceServer).RegisterAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alert.AlertService/RegisterAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertServiceServer).RegisterAgent(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AlertService_ServiceDesc is the grpc.ServiceDesc for AlertService service.
var AlertService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "alert.AlertService",
	HandlerType: (*AlertServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAgent",
			Handler:    _AlertService_RegisterAgent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAlerts",
			Handler:       _AlertService_StreamAlerts_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/alert.proto",
}
